[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install -g tweet-harvest"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[phases.start]
cmd = "gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT"